---

- include_vars:
    dir: "/etc/ansible/vars"
    extensions: ['yml']
    files_matching: '.*\.yml'
    ignore_files:
      - '.*\.swp'
    depth: 1

- name: 'Start ftpd docker container'
  docker:
    name: "{{ docker_ftpd_container_name }}"
    image: stilliard/pure-ftpd:hardened
    ports:
      - '0.0.0.0:21:21'
      - '0.0.0.0:30000:30000'
      - '0.0.0.0:30001:30001'
      - '0.0.0.0:30002:30002'
      - '0.0.0.0:30003:30003'
      - '0.0.0.0:30004:30004'
      - '0.0.0.0:30005:30005'
      - '0.0.0.0:30006:30006'
      - '0.0.0.0:30007:30007'
      - '0.0.0.0:30008:30008'
      - '0.0.0.0:30009:30009'
    env:
      PUID: '0'
      PGID: '0'
      VERSION: 'latest'
      PUBLICHOST: 'localhost'
      ADDED_FLAGS: '-d -d'
    volumes:
      - '{{ ftpusers_directory }}:/home/ftpusers'
      - '{{ ftp_config_directory }}:/etc/pure-ftpd/passwd'
      - '/etc/localtime:/etc/localtime:ro'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "{{ docker_ftpd_container_name }}"
